erDiagram
    Metadata {
        nvarchar(max) resourceID
        nvarchar(max) resourceTitle
        nvarchar(max) resourceDescription
        nvarchar(max) resourceLanguage
        nvarchar(max) contentType
        nvarchar(max) crs
        nvarchar(max) resourceURL
        nvarchar(max) catalogServiceURL
        nvarchar(max) searchFilterType
        nvarchar(max) searchFilterValue
        nvarchar(max) topic
        nvarchar(max) levelNUTS
        nvarchar(max) organisationName
        nvarchar(max) organisationEmail
        nvarchar(max) organisationWebpage
        datetime datePublished
        datetime dateStartCollection
        datetime dateEndCollection
        datetime dateNextUpdate
        nvarchar(max) updateFrequency
        nvarchar(max) keywords
        nvarchar(max) legalInstrument
        nvarchar(max) addInfo
        nvarchar(max) fileUpload
        nvarchar(5) rn3_dataProviderCode
        nvarchar(100) rn3_recordId
        int rn3_snapshotId
    }
